Prince/ fix: chart loading issue
deriv-com/smarttrader pull request #796
Opened 2024-08-12 11:40 UTC by prince-deriv

2024-08-12 11:47 UTC, meenakshi-deriv approved these changes

2024-08-12 11:49 UTC, jia-deriv approved these changes

2024-08-12 12:11 UTC, Nuzhy-Deriv approved these changes

2024-08-12 13:00 UTC, maryia-deriv requested changes

2024-08-12 13:00 UTC, maryia-deriv commented on src/javascript/app/pages/bottom/graph.jsx
> +const Graph = ({ onLoad,onUnload }) => {
```suggestion
const Graph = ({ onLoad, onUnload }) => {
```

2024-08-12 13:00 UTC, maryia-deriv commented on src/javascript/app/pages/bottom/tabs.jsx
> +    const [isShowGraph,setIsShowGraph] = useState(false);
```suggestion
    const [isShowGraph, setIsShowGraph] = useState(false);
```

2024-08-12 13:59 UTC, maryia-deriv approved these changes

2024-08-13 02:40 UTC, balakrishna-deriv approved these changes

2024-08-13 02:42 UTC, ahmadtaimoor-deriv approved these changes

2024-08-13 05:20 UTC, merged